// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF56o4ROviGrNFfOAeKZT0DB0zBcQ6m-Q',
    appId: '1:893727018574:web:a2f26d8e67379bdc99bd1f',
    messagingSenderId: '893727018574',
    projectId: 'hermodr-smr',
    authDomain: 'hermodr-smr.firebaseapp.com',
    storageBucket: 'hermodr-smr.firebasestorage.app',
    measurementId: 'G-2196WRL7BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjekeFOKM3HiVK1La7zp9qyU9pZR4gnzY',
    appId: '1:893727018574:android:900f2c0d24b668ad99bd1f',
    messagingSenderId: '893727018574',
    projectId: 'hermodr-smr',
    storageBucket: 'hermodr-smr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpsuV-f7K5qWjyVQ-lYw7SKIW-Jibx7M',
    appId: '1:893727018574:ios:234ac576c4b0dc6d99bd1f',
    messagingSenderId: '893727018574',
    projectId: 'hermodr-smr',
    storageBucket: 'hermodr-smr.firebasestorage.app',
    iosBundleId: 'com.example.hermodr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpsuV-f7K5qWjyVQ-lYw7SKIW-Jibx7M',
    appId: '1:893727018574:ios:234ac576c4b0dc6d99bd1f',
    messagingSenderId: '893727018574',
    projectId: 'hermodr-smr',
    storageBucket: 'hermodr-smr.firebasestorage.app',
    iosBundleId: 'com.example.hermodr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF56o4ROviGrNFfOAeKZT0DB0zBcQ6m-Q',
    appId: '1:893727018574:web:9bba05d53b1cd51099bd1f',
    messagingSenderId: '893727018574',
    projectId: 'hermodr-smr',
    authDomain: 'hermodr-smr.firebaseapp.com',
    storageBucket: 'hermodr-smr.firebasestorage.app',
    measurementId: 'G-B3CHJ4KDK3',
  );
}